"""Regenerate responsive portfolio images (requires Python and Pillow)."""

from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parents[1]
assets = root / "src/assets"
output = assets / "optimized"
output.mkdir(exist_ok=True)
imports = []
entries = []

for index, path in enumerate(sorted(assets.iterdir())):
    if path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
        continue
    with Image.open(path) as source:
        image = ImageOps.exif_transpose(source).convert("RGB")
        variants = []
        for size in (640, 1600):
            resized = image.copy()
            # Bound width, preserving aspect ratio and avoiding upscaling.
            if resized.width > size:
                resized = resized.resize(
                    (size, round(resized.height * size / resized.width)),
                    Image.Resampling.LANCZOS,
                )
            filename = f"{path.stem}-{size}.webp"
            resized.save(output / filename, "WEBP", quality=82, method=6)
            name = f"image{index}_{size}"
            imports.append(f"import {name} from '../assets/optimized/{filename}'")
            variants.append((name, resized.width, resized.height))
        small, large = variants
        entries.append(
            f"  [{large[0]}]: {{ small: {small[0]}, smallWidth: {small[1]}, "
            f"width: {large[1]}, height: {large[2]} }}"
        )

manifest = "\n".join(imports) + "\n\n"
manifest += "// Generated by scripts/optimize-images.py.\n"
manifest += "export const responsiveImages: Record<string, { small: string; smallWidth: number; width: number; height: number }> = {\n"
manifest += ",\n".join(entries) + "\n}\n"
(root / "src/data/responsiveImages.ts").write_text(manifest)
